### ISSUE TITLE
MemoryError while preprocessing the data

### ISSUE THREAD

**Issue by Salomeeeee** [megagonlabs/cocosum#1]
Hello! I tried to reproduce your work, but always encountered MemoryError while calling _pairing_ function in _prep.py_ due to the limited memory size, so could you please offer _train_comm_pair.jsonl_? Thanks a lot!!!

**Comment by isomap** [comment]
Thanks for your interest!

Sorry, due to the license problem, we don't plan to release our preprocessed dataset, but I'd be happy to help you to solve the issue you have now.
So, could you tell me more about the issue you are facing now? Which line did you get the memory error? (maybe this line? https://github.com/megagonlabs/cocosum/blob/main/prep.py#L154)

Thanks!

**Comment by Salomeeeee** [comment]
Yes, the line which triggered the memory error is L154, and the error information is as below:
![dbd893e0df8f26d74e31c0285fded38](https://user-images.githubusercontent.com/70430556/177937579-62184be0-d5f5-413f-bc27-a1929c0ff757.png)
The similarity matrix overwhelmed my memory space. When I modified the code to iterate through each 1-D array in _tgt_vec_, it took 2k+ hours to finish pairing. Maybe some acceleration technology is needed?
Thank you very much for helping><

**Comment by isomap** [comment]
Thanks for the info!

This was not a problem for our machine used in the experiment, so we didn't optimize this implementation.
I don't have time to fix this issue now, but I'd suggest using nearest-neighbors by `sklearn` (used in this line: https://github.com/megagonlabs/cocosum/blob/main/prep.py#L125) or similarity search by `faiss` (This can be a helpful tutorial: https://github.com/matsui528/faiss_tips#nearest-neighbor-search-cpu) to make this similarity search fast and space-efficient.

I'm sorry I cannot give you full support. I hope this will help you reproduce our study.

Thank you!

**Comment by Salomeeeee** [comment]
That's OK! The problem seemed to be solved now, and I really appreciate your generous help:-)

**Comment by belizgunel** [comment]
Hi! I was wondering how you ended up solving this problem? My process gets killed without mentioning any errors, and the machine I'm using has 192 GB RAM...

**Comment by Salomeeeee** [comment]
> Hi! I was wondering how you ended up solving this problem? My process gets killed without mentioning any errors, and the machine I'm using has 192 GB RAM...

Hello! I just used the package faiss to modify the line 154 in prep.py. Maybe you can refer to the tutorial above :-)

**Comment by lovodkin93** [comment]
Hi,
I also keep getting a similar error:
```
numpy.core._exceptions.MemoryError: Unable to allocate 84.6 GiB for an array with shape (11355303385,) and data type
 int64
```

@Salomeeeee @isomap  Could you please elaborate on how to use faiss to make the code work?
Thanks!

**Comment by isomap** [comment]
Duplicate #3
