### ISSUE TITLE
A problem while saving the trained model

### ISSUE THREAD

**Issue by Salomeeeee** [megagonlabs/cocosum#2]
Sorry to bother you again since the preprocessing was done!
I encountered another error while training the base  opinion summarization models, in https://github.com/megagonlabs/cocosum/blob/main/train.py#L35:
![c8020d0387274932e18559b1d397766](https://user-images.githubusercontent.com/70430556/178699277-a34c1fa1-b4dc-4c36-b72b-6bf8a16c9f5c.png)
It seems that the trained model can't be saved due to a conflict between _pickle_ and the nested function **lr_lambda** in _transformers_. (https://github.com/megagonlabs/cocosum/blob/main/model.py#L185 -> https://github.com/huggingface/transformers/blob/v4.20.1/src/transformers/optimization.py#L94) 
Did you meet the problem while running the code? Thank you!

**Comment by isomap** [comment]
No worries. I didn't face this issue. Could you double-check the requirements.txt again and please use the same version of dependencies?

Thanks :)
